### PR TITLE
Add data-driven hexcasting module (for internalized pigment)

### PR DESCRIPTION
**Pull request by leo60228**
See https://gamma-delta.github.io/HexMod/#items/pigments for info on pigments.

### CODE REVIEW

**Comment by gamma-delta** [comment]
ooh!

I'm not sure how Switchy works internally but we might be releasing some breaking changes to how colorizers are stored. If it just spoofs different CC sets, then it should work fine though. But probably check again once 1.20 rolls around

**Comment by sisby-folk** [comment]
@gamma-delta in this case (CCA Modules) Switchy works by running the serialiser when swapping off of a preset, shelving the data, and running the deserializer when swapping onto a preset.

🎉 This means there's effectively a second cold storage for CCA data, so if you're intending on a datafix for 1.20 we'll have to make sure the fallbacks are set correctly, yep!

As a sidenote, switchy-cardinal modules (the json files) can also be put in the mod it adds compatibility for. In this case, the `ifModsLoaded` tag is not needed.

**Comment by gamma-delta** [comment]
1.20 Hexcasting is not meant to be backwards compatible so no worries there... and we're probably releasing a non-backwards-compatible 0.11 on 1.19 as a sendoff.

I've given myself a note in the langfile to mention Switchy compat in the patchi book once it is merged

**Review by sleepingdragoninn — APPROVED** [review]
🎉 Looks good! lovely attention to detail

**Comment by sisby-folk** [comment]
Released in [v2.1.0](https://github.com/sisby-folk/switchy/releases/tag/v2.1.0)

**Pull request merged**
